### PR TITLE
Fix flex styling on JM round management screen

### LINKED ISSUE #1669: What is this Box that says “N…” I’m guessing some text is cutoff? This screenshot is taken with my chrome window zoomed in but I see the same thing on normal 100% zoom too
What is this Box that says “N…” I’m guessing some text is cutoff? This screenshot is taken with my chrome window zoomed in but I see the same thing on normal 100% zoom too.
cc @jonah @roe as this seems like an actual bug potentially

Issue automatically created from slack feedback reported by caroline 
https://votingworks.slack.com/archives/C01F2CH62TS/p1667430278825789?thread_ts=1667430278.825789&cid=C01F2CH62TS

### PR DESCRIPTION
**Pull request by jonahkagan**
Fixes #1669 

Screen Shot 2022-11-02 at 5 01 28 PM
Screen Shot 2022-11-02 at 5 18 20 PM

### CODE REVIEW

File: client/src/components/JurisdictionAdmin/RoundManagement.tsx [hunk 1]
```diff
@@ -28,9 +28,8 @@ import { Row, Column } from '../Atoms/Layout'
 
 const Inner = styled(InnerAtom).attrs({ flexDirection: 'column' })``
 
-const SpacedDiv = styled(Card).attrs({ elevation: 1 })`
+const Panel = styled(Card).attrs({ elevation: 1 })`
   margin-bottom: 30px;
-  width: 100%;
```
Comment (arsalansufi) [inline client/src/components/JurisdictionAdmin/RoundManagement.tsx:33]: 🙈

I added this for https://github.com/votingworks/arlo/pull/1661 and tested it before https://github.com/votingworks/arlo/pull/1651 was merged but not after - thank you for fixing!

**Review by arsalansufi — APPROVED** [review]

File: client/src/components/JurisdictionAdmin/RoundManagement.tsx (hunk 1 above)
Comment (jonahkagan) [reply client/src/components/JurisdictionAdmin/RoundManagement.tsx:33]: Oh interesting! I was wondering what changed. It had me quite confused

Comment (jonahkagan) [reply client/src/components/JurisdictionAdmin/RoundManagement.tsx:33]: Hmm, now I wonder why removing this line alone didn't fix it
