### PR TITLE
Statusbox fix for batch comparison

### LINKED ISSUE #1238: Bug: AA status bar shows incorrect status on batch audits?
For some reason, the status bar at the top of the AA interface shows that all audit boards are complete immediately after you start a batch audit (when no audit boards are complete?) Can we correct or remove that sentence?

### PR DESCRIPTION
**Pull request by MorganLove**
**Description**

Closes #1238 

**Testing**

- Currently no test updates

**Notes**

So the bug was in JA login after Batch Audit is launched. Basically, for Batch Comparison, as it's about batches, the Audit Board API has numSampledBallots & numAuditedBallots both always as 0. Due to that it shows "1 of 1 Audit Boards complete."

For now, this is a frontend fix by popping "1 of 1 Audit Boards complete" from the details & not thus showing this line for Batch Comparison.

As a backend fix, we would need to update the API to calculate numSampledBallots based on total numBallots across all Batches.

### CODE REVIEW

File: client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx [hunk 1]
```diff
@@ -367,6 +367,10 @@ export const JurisdictionAdminStatusBox = ({
     const details = [
       `${numCompleted} of ${auditBoards.length} audit boards complete.`,
```
Comment (jonahkagan) [inline client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx:368]: thinking about this more, this sentence really only makes sense for online data entry audits, since in all offline audits, all of the audit board results are entered at once

Comment (MorganLove) [reply client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx:368]: @jonahkagan yeah, good point. Which means this should work fine for this, but we could also just filter it out for all offline audits. I'm not seeing that online/offline is available in the status box yet, though. I wonder how much it would take to add that in...

Comment (jonahkagan) [reply client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx:368]: it's in the audit settings, so should be easy

Comment (MorganLove) [reply client/src/components/MultiJurisdictionAudit/StatusBox/index.tsx]: @jonahkagan okay, let me know what you think of my latest update.

File: client/src/components/MultiJurisdictionAudit/index.tsx [hunk 2]
```diff
@@ -225,6 +225,7 @@ export const JurisdictionAdminView: React.FC = () => {
           auditBoards={auditBoards}
           auditType={auditSettings.auditType}
           auditName={auditSettings.auditName}
+          isAuditOnline={!!auditSettings.online}
```
Comment (jonahkagan) [inline client/src/components/MultiJurisdictionAudit/index.tsx:228]: `auditSettings.online` should already be a boolean, so i don't think the `!!` is necessary. also at this point i feel like we might as well pass in the whole `auditSettings` object, though this way is fine too

File: client/src/components/MultiJurisdictionAudit/StatusBox/index.test.tsx [hunk 3]
```diff
@@ -459,6 +465,34 @@ describe('StatusBox', () => {
...
+            batchTallies={{ file: null, processing: null }}
+            cvrs={{ file: null, processing: null }}
+            auditType="BALLOT_POLLING"
+            auditName="Test Audit"
+            isAuditOnline={false}
+          />
+        </Router>
+      )
+      screen.getByText('Round 1 of the audit is in progress.')
+      screen.queryByText('1 of 1 audit boards complete.')
```
Comment (jonahkagan) [inline client/src/components/MultiJurisdictionAudit/StatusBox/index.test.tsx:487]: remove this line

**Review by jonahkagan — APPROVED** [review]

File: client/src/components/MultiJurisdictionAudit/index.tsx (hunk 2 above)
Comment (MorganLove) [reply client/src/components/MultiJurisdictionAudit/index.tsx:228]: @jonahkagan it's actually `boolean | null` which is why I went this route.
